### ISSUE TITLE
ETA & Features

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/FactionShock#3]
Just like to ask what kind of ETA you are one for a first release. Seems like an interesting project

If you have any new features in it to share, please post them below. I'm extremely interested in this project

**Comment by drtshock** [comment]
uh, long in the future ;o currently working on hcfactions and factionsuuid still :\

**Comment by MoeXIV** [comment]
@drtshock Can you explain some of the new features in this project, and if you were "influenced" to start (paid), would you start developing?

Be sure to also answer the first question (what features will be added), as you forgot to in your last response.

**Comment by drtshock** [comment]
If I was paid my usual hourly rate, hell yeah I'd start again. But I have other projects to work on where I'm getting my hourly rate.
